#!/bin/bash

temp=$(mktemp -t test.XXXXXX)
temp2=$(mktemp -t test2.XXXXXX)

diskspace() {
	df -k > $temp
	dialog --textbox $temp 20 60
}

whoseon() {
	who > $temp
	dialog --textbox $temp 20 50
}

menusage() {
	cat /proc/meminfo > $temp
	dialog --textbox $temp 20 50
}

while [ 1 ]
do
	dialog --menu "系统用户系统" 20 30 10 1 "显示磁盘空间" 2 "显示当前用户" 3 "显示内存使用情况" 0 "退出" 2>$temp2
	if [ $? -eq 1 ]
	then 
		break
	fi
selection=$(cat $temp2)

case $selection in
	1)
	diskspace ;;
	2)
	whoseon ;;
	3)
	menusage ;;
	0)
	break ;;
	*)
	dialog --msgbox "Sorry, invalid selection" 10 30
esac
done
rm -f $temp 2>/dev/null
rm -f $temp2 2>/dev/null


